# Generated by Django 3.1.5 on 2021-02-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('relationtype', models.CharField(max_length=20)),
                ('relativename', models.CharField(max_length=20)),
                ('birthaddress', models.CharField(max_length=20)),
                ('birthdate', models.DateField(max_length=20)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('rdate', models.DateField(max_length=20)),
                ('fdate', models.DateField(max_length=20)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
    ]
