# Generated by Django 3.1.5 on 2021-02-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_Aadhar', '0002_auto_20210221_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapp',
            name='addf',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newapp',
            name='addfname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newapp',
            name='agef',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newapp',
            name='agefname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newapp',
            name='phf',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
