# Generated by Django 3.1.5 on 2021-02-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_Aadhar', '0003_auto_20210222_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapp',
            name='addf',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='agef',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='phf',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
