# Generated by Django 3.1.5 on 2021-02-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_Aadhar', '0004_auto_20210226_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapp',
            name='uid',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
