# Generated by Django 3.1.5 on 2021-03-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_Aadhar', '0005_newapp_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapp',
            name='addf',
            field=models.ImageField(blank=True, null=True, upload_to='images/address_proof/'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='agef',
            field=models.ImageField(blank=True, null=True, upload_to='images/age_proof/'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='phf',
            field=models.ImageField(blank=True, null=True, upload_to='images/photograph/'),
        ),
    ]
