# Generated by Django 3.1.5 on 2021-03-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_Aadhar', '0006_auto_20210302_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newapp',
            old_name='uid',
            new_name='vid',
        ),
    ]
